version: '3'

services:
  fastapi:
    image: recommenderlpgg
    container_name: fastapi
    ports:
      - "80:80"
    networks:
      - app-network

  streamlit:
    build: .
    container_name: streamlit
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - fastapi

networks:
  app-network:
    driver: bridge
